import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { Header } from "@/components/my/Header";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/my/AppSideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Header></Header>
      <div>
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full pt-13 flex">
            <div className="h-full border-[#E4E4E7] border w-15 border-l-0 border-t-0">
              <div className="flex justify-center pt-6">
                <SidebarTrigger />
              </div>
            </div>
            <div className="bg-accent w-[85vw] h-full">{children}</div>
          </main>
        </SidebarProvider>
      </div>
    </div>
  );
}
